// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: mitts.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMitt = `-- name: CreateMitt :one
WITH inserted AS (
    INSERT INTO mitts (
        author, content
    ) VALUES (
        $1, $2
    )
    RETURNING id, author, content, created_at, updated_at
)
SELECT i.id, i.author, i.content, i.created_at, i.updated_at, us.name AS author_name, COUNT(ms.id) AS likes_count
FROM inserted AS i
LEFT JOIN mitts_likes AS ms ON ms.mitt_id = i.id
LEFT JOIN users AS us ON us.id = i.author
GROUP BY
    i.id,
    i.author,
    i.content,
    i.created_at,
    i.updated_at,
    us.name
LIMIT 1
`

type CreateMittParams struct {
	Author  uuid.UUID
	Content string
}

type CreateMittRow struct {
	ID         uuid.UUID
	Author     uuid.UUID
	Content    string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	AuthorName pgtype.Text
	LikesCount int64
}

func (q *Queries) CreateMitt(ctx context.Context, arg CreateMittParams) (CreateMittRow, error) {
	row := q.db.QueryRow(ctx, createMitt, arg.Author, arg.Content)
	var i CreateMittRow
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.LikesCount,
	)
	return i, err
}

const deleteMitt = `-- name: DeleteMitt :exec
DELETE FROM mitts
WHERE id = $1
`

func (q *Queries) DeleteMitt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMitt, id)
	return err
}

const deleteMittLike = `-- name: DeleteMittLike :exec
DELETE FROM mitts_likes
WHERE user_id = $1 AND mitt_id = $2
`

type DeleteMittLikeParams struct {
	UserID uuid.UUID
	MittID uuid.UUID
}

func (q *Queries) DeleteMittLike(ctx context.Context, arg DeleteMittLikeParams) error {
	_, err := q.db.Exec(ctx, deleteMittLike, arg.UserID, arg.MittID)
	return err
}

const feed = `-- name: Feed :many
SELECT m.id, m.author, m.content, m.created_at, m.updated_at, us.name AS author_name, COUNT(ms.id) AS likes_count
FROM mitts AS m
LEFT JOIN mitts_likes AS ms ON ms.mitt_id = m.id
LEFT JOIN users AS us ON us.id = m.author
GROUP BY
    m.id,
    m.author,
    m.content,
    m.created_at,
    m.updated_at,
    us.name
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type FeedParams struct {
	Limit  int32
	Offset int32
}

type FeedRow struct {
	ID         uuid.UUID
	Author     uuid.UUID
	Content    string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	AuthorName pgtype.Text
	LikesCount int64
}

func (q *Queries) Feed(ctx context.Context, arg FeedParams) ([]FeedRow, error) {
	rows, err := q.db.Query(ctx, feed, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedRow
	for rows.Next() {
		var i FeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.LikesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserMitts = `-- name: GetAllUserMitts :many
SELECT m.id, m.author, m.content, m.created_at, m.updated_at, us.name AS author_name, COUNT(ms.id) AS likes_count
FROM mitts AS m
LEFT JOIN mitts_likes AS ms ON ms.mitt_id = m.id
LEFT JOIN users AS us ON us.id = m.author
WHERE m.author = $3
GROUP BY
    m.id,
    m.author,
    m.content,
    m.created_at,
    m.updated_at,
    us.name
ORDER BY m.created_at
LIMIT $1 OFFSET $2
`

type GetAllUserMittsParams struct {
	Limit  int32
	Offset int32
	Author uuid.UUID
}

type GetAllUserMittsRow struct {
	ID         uuid.UUID
	Author     uuid.UUID
	Content    string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	AuthorName pgtype.Text
	LikesCount int64
}

func (q *Queries) GetAllUserMitts(ctx context.Context, arg GetAllUserMittsParams) ([]GetAllUserMittsRow, error) {
	rows, err := q.db.Query(ctx, getAllUserMitts, arg.Limit, arg.Offset, arg.Author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserMittsRow
	for rows.Next() {
		var i GetAllUserMittsRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.LikesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMitt = `-- name: GetMitt :one
SELECT m.id, m.author, m.content, m.created_at, m.updated_at, us.name AS author_name, COUNT(ms.id) AS likes_count
FROM mitts AS m
LEFT JOIN mitts_likes AS ms ON ms.mitt_id = m.id
LEFT JOIN users AS us ON us.id = m.author
WHERE m.id = $1
GROUP BY
    m.id,
    m.author,
    m.content,
    m.created_at,
    m.updated_at,
    us.name
LIMIT 1
`

type GetMittRow struct {
	ID         uuid.UUID
	Author     uuid.UUID
	Content    string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	AuthorName pgtype.Text
	LikesCount int64
}

func (q *Queries) GetMitt(ctx context.Context, id uuid.UUID) (GetMittRow, error) {
	row := q.db.QueryRow(ctx, getMitt, id)
	var i GetMittRow
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.LikesCount,
	)
	return i, err
}

const isMittLikedByUser = `-- name: IsMittLikedByUser :one
SELECT 1 FROM mitts_likes
WHERE user_id = $1 AND mitt_id = $2
`

type IsMittLikedByUserParams struct {
	UserID uuid.UUID
	MittID uuid.UUID
}

func (q *Queries) IsMittLikedByUser(ctx context.Context, arg IsMittLikedByUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, isMittLikedByUser, arg.UserID, arg.MittID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const likeMitt = `-- name: LikeMitt :exec
INSERT INTO mitts_likes (
    user_id, mitt_id
) VALUES (
    $1, $2
)
`

type LikeMittParams struct {
	UserID uuid.UUID
	MittID uuid.UUID
}

func (q *Queries) LikeMitt(ctx context.Context, arg LikeMittParams) error {
	_, err := q.db.Exec(ctx, likeMitt, arg.UserID, arg.MittID)
	return err
}

const updateMitt = `-- name: UpdateMitt :one
WITH updated AS (
    UPDATE mitts m
    SET
        content = $1,
        updated_at = NOW()
    WHERE m.id = $2
    RETURNING id, author, content, created_at, updated_at
)
SELECT u.id, u.author, u.content, u.created_at, u.updated_at, us.name AS author_name, COUNT(ms.id) AS likes_count
FROM updated AS u
LEFT JOIN mitts_likes AS ms ON ms.mitt_id = u.id
LEFT JOIN users AS us ON us.id = u.author
GROUP BY
    u.id,
    u.author,
    u.content,
    u.created_at,
    u.updated_at,
    us.name
LIMIT 1
`

type UpdateMittParams struct {
	Content string
	ID      uuid.UUID
}

type UpdateMittRow struct {
	ID         uuid.UUID
	Author     uuid.UUID
	Content    string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	AuthorName pgtype.Text
	LikesCount int64
}

func (q *Queries) UpdateMitt(ctx context.Context, arg UpdateMittParams) (UpdateMittRow, error) {
	row := q.db.QueryRow(ctx, updateMitt, arg.Content, arg.ID)
	var i UpdateMittRow
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorName,
		&i.LikesCount,
	)
	return i, err
}
