// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storage

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Mitt struct {
	ID        uuid.UUID
	Author    uuid.UUID
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type MittsLike struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	MittID  uuid.UUID
	LikedAt pgtype.Timestamp
}

type User struct {
	ID       uuid.UUID
	Login    string
	Name     string
	Password string
}

type UsersFollow struct {
	ID         uuid.UUID
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}
