// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package storage

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, name) VALUES ($1, $2)
RETURNING id
`

type CreateUserParams struct {
	Login string
	Name  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
