{
 "title": "Mitter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Mitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(mitter_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mitter_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mitts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mitter_mitts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Likes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mitter_mitts_likes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Viewed in feed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mitter_mitts_feed_viewed", "legendFormat": "__auto" }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Goroutines",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"mitter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}