global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'mitter'
    scrape_interval: 3s
    static_configs:
      - targets: ['backend:8080']
